import { mockobjectevent } from "@/app/(admin)/events/page"

export const simulatedEvents: mockobjectevent[] = [
    {
        id: 1,
        idDueño: 2,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "habilitado",
    },
    {
        id: 2,
        idDueño: 2,
        startDate: "1/11/2003",
        endDate: "2/12/2003",
        info: "Evento de prueba numero 2 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "en espera",
    },
    {
        id: 3,
        idDueño: 3,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 3 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "en espera",
    },
    {
        id: 4,
        idDueño: 4,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 4 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "habilitado",
    },
    {
        id: 5,
        idDueño: 5,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 5 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "en espera",
    },
    {
        id: 6,
        idDueño: 6,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 6 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "rechazado",
    },
    {
        id: 7,
        idDueño: 7,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 7 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "rechazado",
    },
    {
        id: 8,
        idDueño: 8,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 8 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "habilitado",
    },
    {
        id: 9,
        idDueño: 9,
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        info: "Evento de prueba numero 9 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        image: "https://images.ygoprodeck.com/images/cards/74677427.jpg",
        estado: "en espera",
    }
]